version: '3.3'
services:
  udp-proxy-2020:
    container_name: udp-proxy-2020
    image: synfinatic/udp-proxy-2020:latest
    environment:
      - PORTS=9003
      - INTERFACES=eth0,eth1
      - EXTRA_ARGS=-L debug
      - TIMEOUT=250
      - CACHETTL=90
    restart: unless-stopped
    networks:
      macvlan_roon:
        ipv4_address: 192.168.5.2
      macvlan_main:
        ipv4_address: 192.168.15.2

networks:
    macvlan_roon:
      external: true
    macvlan_main:
      external: true
